function [BC,Choice] = Choose
name={'West...','East...','South...','North...','Bottom...','Upper...'};
for i=1:6
choice = 'Pressure Gradient Specified'; %Default
value = 0; %Default
d = dialog('Position',[600 500 250 200],'Name',name{i});
txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 130 210 40],...
    'String','What kind of boundary you have?',...
    'FontSize',10);

popup = uicontrol('Parent',d,...
    'Style','popup',...
    'Position',[50 120 150 25],...
    'String',{'Pressure Gradient Specified';'Pressure Specified'},...
    'Callback',@popup_callback);
edit = uicontrol('Parent',d,...
    'Style','edit',...
    'Position',[50 90 150 20],...
    'String',0,...
    'Value',0,...
    'Callback',@value_callback);
btn = uicontrol('Parent',d,...
    'Position',[89 20 70 25],...
    'String','OK!',...
    'Callback','delete(gcf)');
% Wait for d to close before running to completion
uiwait(d);
Choice{i}=choice;
Value(i)=value;
end
BC.W=Value(1);BC.E=Value(2);BC.S=Value(3);BC.N=Value(4);BC.B=Value(5);BC.U=Value(6);
    function popup_callback(popup,event)
        idx = popup.Value;
        popup_items = popup.String;
        choice = string(popup_items{idx});
    end
    function value_callback(edit,event)
        value = str2num(edit.String);
    end
end